export type ErrorCode = keyof typeof ErrorCodes;

export class ContractAnalysisError extends Error {
  code: ErrorCode;
  severity: 'error' | 'warning' | 'info';
  timestamp: string;
  context?: any;
  isRetryable?: boolean;
  action?: {
    label: string;
    handler: () => void;
  };

  constructor(
    message: string,
    code: ErrorCode,
    severity: 'error' | 'warning' | 'info' = 'error',
    context?: any,
    isRetryable?: boolean,
    action?: {
      label: string;
      handler: () => void;
    }
  ) {
    super(message);
    this.name = 'ContractAnalysisError';
    this.code = code;
    this.severity = severity;
    this.timestamp = new Date().toISOString();
    this.context = context;
    this.isRetryable = isRetryable;
    this.action = action;
  }
}

export const ErrorCodes = {
  // Contract Analysis Errors
  CONTRACT_ANALYSIS_ERROR: 'CONTRACT_ANALYSIS_ERROR',
  INVALID_CONTRACT_FORMAT: 'INVALID_CONTRACT_FORMAT',
  MISSING_REQUIRED_SECTIONS: 'MISSING_REQUIRED_SECTIONS',
  INVALID_CONTRACT_STRUCTURE: 'INVALID_CONTRACT_STRUCTURE',
  CONTRACT_PROCESSING_ERROR: 'CONTRACT_PROCESSING_ERROR',
  CONTRACT_VALIDATION_ERROR: 'CONTRACT_VALIDATION_ERROR',
  CONTRACT_PARSING_ERROR: 'CONTRACT_PARSING_ERROR',
  CONTRACT_ANALYSIS_TIMEOUT: 'CONTRACT_ANALYSIS_TIMEOUT',
  CONTRACT_ANALYSIS_LIMIT_EXCEEDED: 'CONTRACT_ANALYSIS_LIMIT_EXCEEDED',
  CONTRACT_ANALYSIS_SERVICE_UNAVAILABLE: 'CONTRACT_ANALYSIS_SERVICE_UNAVAILABLE',
  CONTRACT_ANALYSIS_INVALID_RESPONSE: 'CONTRACT_ANALYSIS_INVALID_RESPONSE',
  CONTRACT_ANALYSIS_PARTIAL_SUCCESS: 'CONTRACT_ANALYSIS_PARTIAL_SUCCESS',
  CONTRACT_ANALYSIS_INCOMPLETE: 'CONTRACT_ANALYSIS_INCOMPLETE',
  CONTRACT_ANALYSIS_INCONSISTENT: 'CONTRACT_ANALYSIS_INCONSISTENT',
  CONTRACT_ANALYSIS_AMBIGUOUS: 'CONTRACT_ANALYSIS_AMBIGUOUS',
  CONTRACT_ANALYSIS_UNSUPPORTED_FORMAT: 'CONTRACT_ANALYSIS_UNSUPPORTED_FORMAT',
  CONTRACT_ANALYSIS_UNSUPPORTED_LANGUAGE: 'CONTRACT_ANALYSIS_UNSUPPORTED_LANGUAGE',
  CONTRACT_ANALYSIS_UNSUPPORTED_VERSION: 'CONTRACT_ANALYSIS_UNSUPPORTED_VERSION',
  CONTRACT_ANALYSIS_UNSUPPORTED_FEATURE: 'CONTRACT_ANALYSIS_UNSUPPORTED_FEATURE',
  CONTRACT_ANALYSIS_UNSUPPORTED_OPERATION: 'CONTRACT_ANALYSIS_UNSUPPORTED_OPERATION',
  CONTRACT_ANALYSIS_UNSUPPORTED_PARAMETER: 'CONTRACT_ANALYSIS_UNSUPPORTED_PARAMETER',
  CONTRACT_ANALYSIS_UNSUPPORTED_VALUE: 'CONTRACT_ANALYSIS_UNSUPPORTED_VALUE',
  CONTRACT_ANALYSIS_UNSUPPORTED_TYPE: 'CONTRACT_ANALYSIS_UNSUPPORTED_TYPE',
  CONTRACT_ANALYSIS_UNSUPPORTED_METHOD: 'CONTRACT_ANALYSIS_UNSUPPORTED_METHOD',
  CONTRACT_ANALYSIS_UNSUPPORTED_PROTOCOL: 'CONTRACT_ANALYSIS_UNSUPPORTED_PROTOCOL',
  CONTRACT_ANALYSIS_UNSUPPORTED_ENCODING: 'CONTRACT_ANALYSIS_UNSUPPORTED_ENCODING',
  CONTRACT_ANALYSIS_UNSUPPORTED_COMPRESSION: 'CONTRACT_ANALYSIS_UNSUPPORTED_COMPRESSION',
  CONTRACT_ANALYSIS_UNSUPPORTED_ENCRYPTION: 'CONTRACT_ANALYSIS_UNSUPPORTED_ENCRYPTION',
  CONTRACT_ANALYSIS_UNSUPPORTED_SIGNATURE: 'CONTRACT_ANALYSIS_UNSUPPORTED_SIGNATURE',
  CONTRACT_ANALYSIS_UNSUPPORTED_HASH: 'CONTRACT_ANALYSIS_UNSUPPORTED_HASH',
  CONTRACT_ANALYSIS_UNSUPPORTED_KEY: 'CONTRACT_ANALYSIS_UNSUPPORTED_KEY',
  CONTRACT_ANALYSIS_UNSUPPORTED_CERTIFICATE: 'CONTRACT_ANALYSIS_UNSUPPORTED_CERTIFICATE',
  CONTRACT_ANALYSIS_UNSUPPORTED_TOKEN: 'CONTRACT_ANALYSIS_UNSUPPORTED_TOKEN',
  CONTRACT_ANALYSIS_UNSUPPORTED_SESSION: 'CONTRACT_ANALYSIS_UNSUPPORTED_SESSION',
  CONTRACT_ANALYSIS_UNSUPPORTED_USER: 'CONTRACT_ANALYSIS_UNSUPPORTED_USER',
  CONTRACT_ANALYSIS_UNSUPPORTED_ROLE: 'CONTRACT_ANALYSIS_UNSUPPORTED_ROLE',
  CONTRACT_ANALYSIS_UNSUPPORTED_PERMISSION: 'CONTRACT_ANALYSIS_UNSUPPORTED_PERMISSION',
  CONTRACT_ANALYSIS_UNSUPPORTED_POLICY: 'CONTRACT_ANALYSIS_UNSUPPORTED_POLICY',
  CONTRACT_ANALYSIS_UNSUPPORTED_RULE: 'CONTRACT_ANALYSIS_UNSUPPORTED_RULE',
  CONTRACT_ANALYSIS_UNSUPPORTED_CONDITION: 'CONTRACT_ANALYSIS_UNSUPPORTED_CONDITION',
  CONTRACT_ANALYSIS_UNSUPPORTED_ACTION: 'CONTRACT_ANALYSIS_UNSUPPORTED_ACTION',
  CONTRACT_ANALYSIS_UNSUPPORTED_EFFECT: 'CONTRACT_ANALYSIS_UNSUPPORTED_EFFECT',
  CONTRACT_ANALYSIS_UNSUPPORTED_RESOURCE: 'CONTRACT_ANALYSIS_UNSUPPORTED_RESOURCE',
  CONTRACT_ANALYSIS_UNSUPPORTED_ATTRIBUTE: 'CONTRACT_ANALYSIS_UNSUPPORTED_ATTRIBUTE',

  // API Errors
  API_ERROR: 'API_ERROR',
  API_TIMEOUT: 'API_TIMEOUT',
  API_RATE_LIMIT: 'API_RATE_LIMIT',
  API_AUTHENTICATION_ERROR: 'API_AUTHENTICATION_ERROR',
  API_AUTHORIZATION_ERROR: 'API_AUTHORIZATION_ERROR',
  API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
  API_NOT_FOUND: 'API_NOT_FOUND',
  API_METHOD_NOT_ALLOWED: 'API_METHOD_NOT_ALLOWED',
  API_CONFLICT: 'API_CONFLICT',
  API_TOO_MANY_REQUESTS: 'API_TOO_MANY_REQUESTS',
  API_INTERNAL_ERROR: 'API_INTERNAL_ERROR',
  API_SERVICE_UNAVAILABLE: 'API_SERVICE_UNAVAILABLE',
  API_BAD_GATEWAY: 'API_BAD_GATEWAY',
  API_GATEWAY_TIMEOUT: 'API_GATEWAY_TIMEOUT',

  // Network Errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_CONNECTION_ERROR: 'NETWORK_CONNECTION_ERROR',
  NETWORK_DNS_ERROR: 'NETWORK_DNS_ERROR',
  NETWORK_SSL_ERROR: 'NETWORK_SSL_ERROR',
  NETWORK_PROXY_ERROR: 'NETWORK_PROXY_ERROR',
  NETWORK_CORS_ERROR: 'NETWORK_CORS_ERROR',
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  NETWORK_REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',
  NETWORK_RESPONSE_INVALID: 'NETWORK_RESPONSE_INVALID',
  NETWORK_RESPONSE_TIMEOUT: 'NETWORK_RESPONSE_TIMEOUT',
  NETWORK_RESPONSE_ERROR: 'NETWORK_RESPONSE_ERROR',
  NETWORK_RESPONSE_ABORTED: 'NETWORK_RESPONSE_ABORTED',
  NETWORK_RESPONSE_CANCELLED: 'NETWORK_RESPONSE_CANCELLED',
  NETWORK_RESPONSE_UNKNOWN: 'NETWORK_RESPONSE_UNKNOWN',

  // Document Processing Errors
  DOCUMENT_PROCESSING_ERROR: 'DOCUMENT_PROCESSING_ERROR',
  DOCUMENT_FORMAT_ERROR: 'DOCUMENT_FORMAT_ERROR',
  DOCUMENT_SIZE_ERROR: 'DOCUMENT_SIZE_ERROR',
  DOCUMENT_TYPE_ERROR: 'DOCUMENT_TYPE_ERROR',
  DOCUMENT_ENCODING_ERROR: 'DOCUMENT_ENCODING_ERROR',
  DOCUMENT_COMPRESSION_ERROR: 'DOCUMENT_COMPRESSION_ERROR',
  DOCUMENT_ENCRYPTION_ERROR: 'DOCUMENT_ENCRYPTION_ERROR',
  DOCUMENT_SIGNATURE_ERROR: 'DOCUMENT_SIGNATURE_ERROR',
  DOCUMENT_HASH_ERROR: 'DOCUMENT_HASH_ERROR',
  DOCUMENT_KEY_ERROR: 'DOCUMENT_KEY_ERROR',
  DOCUMENT_CERTIFICATE_ERROR: 'DOCUMENT_CERTIFICATE_ERROR',
  DOCUMENT_TOKEN_ERROR: 'DOCUMENT_TOKEN_ERROR',
  DOCUMENT_SESSION_ERROR: 'DOCUMENT_SESSION_ERROR',
  DOCUMENT_USER_ERROR: 'DOCUMENT_USER_ERROR',
  DOCUMENT_ROLE_ERROR: 'DOCUMENT_ROLE_ERROR',
  DOCUMENT_PERMISSION_ERROR: 'DOCUMENT_PERMISSION_ERROR',
  DOCUMENT_POLICY_ERROR: 'DOCUMENT_POLICY_ERROR',
  DOCUMENT_RULE_ERROR: 'DOCUMENT_RULE_ERROR',
  DOCUMENT_CONDITION_ERROR: 'DOCUMENT_CONDITION_ERROR',
  DOCUMENT_ACTION_ERROR: 'DOCUMENT_ACTION_ERROR',
  DOCUMENT_EFFECT_ERROR: 'DOCUMENT_EFFECT_ERROR',
  DOCUMENT_RESOURCE_ERROR: 'DOCUMENT_RESOURCE_ERROR',
  DOCUMENT_ATTRIBUTE_ERROR: 'DOCUMENT_ATTRIBUTE_ERROR',

  // OCR Errors
  OCR_ERROR: 'OCR_ERROR',
  OCR_TIMEOUT: 'OCR_TIMEOUT',
  OCR_LIMIT_EXCEEDED: 'OCR_LIMIT_EXCEEDED',
  OCR_SERVICE_UNAVAILABLE: 'OCR_SERVICE_UNAVAILABLE',
  OCR_INVALID_RESPONSE: 'OCR_INVALID_RESPONSE',
  OCR_PARTIAL_SUCCESS: 'OCR_PARTIAL_SUCCESS',
  OCR_INCOMPLETE: 'OCR_INCOMPLETE',
  OCR_INCONSISTENT: 'OCR_INCONSISTENT',
  OCR_AMBIGUOUS: 'OCR_AMBIGUOUS',
  OCR_UNSUPPORTED_FORMAT: 'OCR_UNSUPPORTED_FORMAT',
  OCR_UNSUPPORTED_LANGUAGE: 'OCR_UNSUPPORTED_LANGUAGE',
  OCR_UNSUPPORTED_VERSION: 'OCR_UNSUPPORTED_VERSION',
  OCR_UNSUPPORTED_FEATURE: 'OCR_UNSUPPORTED_FEATURE',
  OCR_UNSUPPORTED_OPERATION: 'OCR_UNSUPPORTED_OPERATION',
  OCR_UNSUPPORTED_PARAMETER: 'OCR_UNSUPPORTED_PARAMETER',
  OCR_UNSUPPORTED_VALUE: 'OCR_UNSUPPORTED_VALUE',
  OCR_UNSUPPORTED_TYPE: 'OCR_UNSUPPORTED_TYPE',
  OCR_UNSUPPORTED_METHOD: 'OCR_UNSUPPORTED_METHOD',
  OCR_UNSUPPORTED_PROTOCOL: 'OCR_UNSUPPORTED_PROTOCOL',
  OCR_UNSUPPORTED_ENCODING: 'OCR_UNSUPPORTED_ENCODING',
  OCR_UNSUPPORTED_COMPRESSION: 'OCR_UNSUPPORTED_COMPRESSION',
  OCR_UNSUPPORTED_ENCRYPTION: 'OCR_UNSUPPORTED_ENCRYPTION',
  OCR_UNSUPPORTED_SIGNATURE: 'OCR_UNSUPPORTED_SIGNATURE',
  OCR_UNSUPPORTED_HASH: 'OCR_UNSUPPORTED_HASH',
  OCR_UNSUPPORTED_KEY: 'OCR_UNSUPPORTED_KEY',
  OCR_UNSUPPORTED_CERTIFICATE: 'OCR_UNSUPPORTED_CERTIFICATE',
  OCR_UNSUPPORTED_TOKEN: 'OCR_UNSUPPORTED_TOKEN',
  OCR_UNSUPPORTED_SESSION: 'OCR_UNSUPPORTED_SESSION',
  OCR_UNSUPPORTED_USER: 'OCR_UNSUPPORTED_USER',
  OCR_UNSUPPORTED_ROLE: 'OCR_UNSUPPORTED_ROLE',
  OCR_UNSUPPORTED_PERMISSION: 'OCR_UNSUPPORTED_PERMISSION',
  OCR_UNSUPPORTED_POLICY: 'OCR_UNSUPPORTED_POLICY',
  OCR_UNSUPPORTED_RULE: 'OCR_UNSUPPORTED_RULE',
  OCR_UNSUPPORTED_CONDITION: 'OCR_UNSUPPORTED_CONDITION',
  OCR_UNSUPPORTED_ACTION: 'OCR_UNSUPPORTED_ACTION',
  OCR_UNSUPPORTED_EFFECT: 'OCR_UNSUPPORTED_EFFECT',
  OCR_UNSUPPORTED_RESOURCE: 'OCR_UNSUPPORTED_RESOURCE',
  OCR_UNSUPPORTED_ATTRIBUTE: 'OCR_UNSUPPORTED_ATTRIBUTE',

  // PDF Processing Errors
  PDF_PROCESSING_ERROR: 'PDF_PROCESSING_ERROR',
  PDF_TIMEOUT: 'PDF_TIMEOUT',
  PDF_LIMIT_EXCEEDED: 'PDF_LIMIT_EXCEEDED',
  PDF_SERVICE_UNAVAILABLE: 'PDF_SERVICE_UNAVAILABLE',
  PDF_INVALID_RESPONSE: 'PDF_INVALID_RESPONSE',
  PDF_PARTIAL_SUCCESS: 'PDF_PARTIAL_SUCCESS',
  PDF_INCOMPLETE: 'PDF_INCOMPLETE',
  PDF_INCONSISTENT: 'PDF_INCONSISTENT',
  PDF_AMBIGUOUS: 'PDF_AMBIGUOUS',
  PDF_UNSUPPORTED_FORMAT: 'PDF_UNSUPPORTED_FORMAT',
  PDF_UNSUPPORTED_LANGUAGE: 'PDF_UNSUPPORTED_LANGUAGE',
  PDF_UNSUPPORTED_VERSION: 'PDF_UNSUPPORTED_VERSION',
  PDF_UNSUPPORTED_FEATURE: 'PDF_UNSUPPORTED_FEATURE',
  PDF_UNSUPPORTED_OPERATION: 'PDF_UNSUPPORTED_OPERATION',
  PDF_UNSUPPORTED_PARAMETER: 'PDF_UNSUPPORTED_PARAMETER',
  PDF_UNSUPPORTED_VALUE: 'PDF_UNSUPPORTED_VALUE',
  PDF_UNSUPPORTED_TYPE: 'PDF_UNSUPPORTED_TYPE',
  PDF_UNSUPPORTED_METHOD: 'PDF_UNSUPPORTED_METHOD',
  PDF_UNSUPPORTED_PROTOCOL: 'PDF_UNSUPPORTED_PROTOCOL',
  PDF_UNSUPPORTED_ENCODING: 'PDF_UNSUPPORTED_ENCODING',
  PDF_UNSUPPORTED_COMPRESSION: 'PDF_UNSUPPORTED_COMPRESSION',
  PDF_UNSUPPORTED_ENCRYPTION: 'PDF_UNSUPPORTED_ENCRYPTION',
  PDF_UNSUPPORTED_SIGNATURE: 'PDF_UNSUPPORTED_SIGNATURE',
  PDF_UNSUPPORTED_HASH: 'PDF_UNSUPPORTED_HASH',
  PDF_UNSUPPORTED_KEY: 'PDF_UNSUPPORTED_KEY',
  PDF_UNSUPPORTED_CERTIFICATE: 'PDF_UNSUPPORTED_CERTIFICATE',
  PDF_UNSUPPORTED_TOKEN: 'PDF_UNSUPPORTED_TOKEN',
  PDF_UNSUPPORTED_SESSION: 'PDF_UNSUPPORTED_SESSION',
  PDF_UNSUPPORTED_USER: 'PDF_UNSUPPORTED_USER',
  PDF_UNSUPPORTED_ROLE: 'PDF_UNSUPPORTED_ROLE',
  PDF_UNSUPPORTED_PERMISSION: 'PDF_UNSUPPORTED_PERMISSION',
  PDF_UNSUPPORTED_POLICY: 'PDF_UNSUPPORTED_POLICY',
  PDF_UNSUPPORTED_RULE: 'PDF_UNSUPPORTED_RULE',
  PDF_UNSUPPORTED_CONDITION: 'PDF_UNSUPPORTED_CONDITION',
  PDF_UNSUPPORTED_ACTION: 'PDF_UNSUPPORTED_ACTION',
  PDF_UNSUPPORTED_EFFECT: 'PDF_UNSUPPORTED_EFFECT',
  PDF_UNSUPPORTED_RESOURCE: 'PDF_UNSUPPORTED_RESOURCE',
  PDF_UNSUPPORTED_ATTRIBUTE: 'PDF_UNSUPPORTED_ATTRIBUTE',

  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED',
  VALIDATION_FORMAT: 'VALIDATION_FORMAT',
  VALIDATION_LENGTH: 'VALIDATION_LENGTH',
  VALIDATION_RANGE: 'VALIDATION_RANGE',
  VALIDATION_PATTERN: 'VALIDATION_PATTERN',
  VALIDATION_TYPE: 'VALIDATION_TYPE',
  VALIDATION_ENUM: 'VALIDATION_ENUM',
  VALIDATION_CUSTOM: 'VALIDATION_CUSTOM',
  VALIDATION_UNIQUE: 'VALIDATION_UNIQUE',
  VALIDATION_EXISTS: 'VALIDATION_EXISTS',
  VALIDATION_NOT_EXISTS: 'VALIDATION_NOT_EXISTS',
  VALIDATION_INVALID: 'VALIDATION_INVALID',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_LENGTH: 'VALIDATION_INVALID_LENGTH',
  VALIDATION_INVALID_RANGE: 'VALIDATION_INVALID_RANGE',
  VALIDATION_INVALID_PATTERN: 'VALIDATION_INVALID_PATTERN',
  VALIDATION_INVALID_TYPE: 'VALIDATION_INVALID_TYPE',
  VALIDATION_INVALID_ENUM: 'VALIDATION_INVALID_ENUM',
  VALIDATION_INVALID_CUSTOM: 'VALIDATION_INVALID_CUSTOM',
  VALIDATION_INVALID_UNIQUE: 'VALIDATION_INVALID_UNIQUE',
  VALIDATION_INVALID_EXISTS: 'VALIDATION_INVALID_EXISTS',
  VALIDATION_INVALID_NOT_EXISTS: 'VALIDATION_INVALID_NOT_EXISTS',

  // Authentication Errors
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHENTICATION_INVALID: 'AUTHENTICATION_INVALID',
  AUTHENTICATION_EXPIRED: 'AUTHENTICATION_EXPIRED',
  AUTHENTICATION_REVOKED: 'AUTHENTICATION_REVOKED',
  AUTHENTICATION_INVALID_TOKEN: 'AUTHENTICATION_INVALID_TOKEN',
  AUTHENTICATION_INVALID_CREDENTIALS: 'AUTHENTICATION_INVALID_CREDENTIALS',
  AUTHENTICATION_INVALID_SESSION: 'AUTHENTICATION_INVALID_SESSION',
  AUTHENTICATION_INVALID_USER: 'AUTHENTICATION_INVALID_USER',
  AUTHENTICATION_INVALID_ROLE: 'AUTHENTICATION_INVALID_ROLE',
  AUTHENTICATION_INVALID_PERMISSION: 'AUTHENTICATION_INVALID_PERMISSION',
  AUTHENTICATION_INVALID_POLICY: 'AUTHENTICATION_INVALID_POLICY',
  AUTHENTICATION_INVALID_RULE: 'AUTHENTICATION_INVALID_RULE',
  AUTHENTICATION_INVALID_CONDITION: 'AUTHENTICATION_INVALID_CONDITION',
  AUTHENTICATION_INVALID_ACTION: 'AUTHENTICATION_INVALID_ACTION',
  AUTHENTICATION_INVALID_EFFECT: 'AUTHENTICATION_INVALID_EFFECT',
  AUTHENTICATION_INVALID_RESOURCE: 'AUTHENTICATION_INVALID_RESOURCE',
  AUTHENTICATION_INVALID_ATTRIBUTE: 'AUTHENTICATION_INVALID_ATTRIBUTE',

  // System Errors
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  SYSTEM_TIMEOUT: 'SYSTEM_TIMEOUT',
  SYSTEM_LIMIT_EXCEEDED: 'SYSTEM_LIMIT_EXCEEDED',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYSTEM_SERVICE_UNAVAILABLE',
  SYSTEM_INVALID_RESPONSE: 'SYSTEM_INVALID_RESPONSE',
  SYSTEM_PARTIAL_SUCCESS: 'SYSTEM_PARTIAL_SUCCESS',
  SYSTEM_INCOMPLETE: 'SYSTEM_INCOMPLETE',
  SYSTEM_INCONSISTENT: 'SYSTEM_INCONSISTENT',
  SYSTEM_AMBIGUOUS: 'SYSTEM_AMBIGUOUS',
  SYSTEM_UNSUPPORTED_FORMAT: 'SYSTEM_UNSUPPORTED_FORMAT',
  SYSTEM_UNSUPPORTED_LANGUAGE: 'SYSTEM_UNSUPPORTED_LANGUAGE',
  SYSTEM_UNSUPPORTED_VERSION: 'SYSTEM_UNSUPPORTED_VERSION',
  SYSTEM_UNSUPPORTED_FEATURE: 'SYSTEM_UNSUPPORTED_FEATURE',
  SYSTEM_UNSUPPORTED_OPERATION: 'SYSTEM_UNSUPPORTED_OPERATION',
  SYSTEM_UNSUPPORTED_PARAMETER: 'SYSTEM_UNSUPPORTED_PARAMETER',
  SYSTEM_UNSUPPORTED_VALUE: 'SYSTEM_UNSUPPORTED_VALUE',
  SYSTEM_UNSUPPORTED_TYPE: 'SYSTEM_UNSUPPORTED_TYPE',
  SYSTEM_UNSUPPORTED_METHOD: 'SYSTEM_UNSUPPORTED_METHOD',
  SYSTEM_UNSUPPORTED_PROTOCOL: 'SYSTEM_UNSUPPORTED_PROTOCOL',
  SYSTEM_UNSUPPORTED_ENCODING: 'SYSTEM_UNSUPPORTED_ENCODING',
  SYSTEM_UNSUPPORTED_COMPRESSION: 'SYSTEM_UNSUPPORTED_COMPRESSION',
  SYSTEM_UNSUPPORTED_ENCRYPTION: 'SYSTEM_UNSUPPORTED_ENCRYPTION',
  SYSTEM_UNSUPPORTED_SIGNATURE: 'SYSTEM_UNSUPPORTED_SIGNATURE',
  SYSTEM_UNSUPPORTED_HASH: 'SYSTEM_UNSUPPORTED_HASH',
  SYSTEM_UNSUPPORTED_KEY: 'SYSTEM_UNSUPPORTED_KEY',
  SYSTEM_UNSUPPORTED_CERTIFICATE: 'SYSTEM_UNSUPPORTED_CERTIFICATE',
  SYSTEM_UNSUPPORTED_TOKEN: 'SYSTEM_UNSUPPORTED_TOKEN',
  SYSTEM_UNSUPPORTED_SESSION: 'SYSTEM_UNSUPPORTED_SESSION',
  SYSTEM_UNSUPPORTED_USER: 'SYSTEM_UNSUPPORTED_USER',
  SYSTEM_UNSUPPORTED_ROLE: 'SYSTEM_UNSUPPORTED_ROLE',
  SYSTEM_UNSUPPORTED_PERMISSION: 'SYSTEM_UNSUPPORTED_PERMISSION',
  SYSTEM_UNSUPPORTED_POLICY: 'SYSTEM_UNSUPPORTED_POLICY',
  SYSTEM_UNSUPPORTED_RULE: 'SYSTEM_UNSUPPORTED_RULE',
  SYSTEM_UNSUPPORTED_CONDITION: 'SYSTEM_UNSUPPORTED_CONDITION',
  SYSTEM_UNSUPPORTED_ACTION: 'SYSTEM_UNSUPPORTED_ACTION',
  SYSTEM_UNSUPPORTED_EFFECT: 'SYSTEM_UNSUPPORTED_EFFECT',
  SYSTEM_UNSUPPORTED_RESOURCE: 'SYSTEM_UNSUPPORTED_RESOURCE',
  SYSTEM_UNSUPPORTED_ATTRIBUTE: 'SYSTEM_UNSUPPORTED_ATTRIBUTE',

  // Transaction related errors
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',
  TRANSACTION_COMMIT_ERROR: 'TRANSACTION_COMMIT_ERROR',
  TRANSACTION_ROLLBACK_ERROR: 'TRANSACTION_ROLLBACK_ERROR',
  
  // Database operation errors
  DOCUMENT_CREATION_ERROR: 'DOCUMENT_CREATION_ERROR',
  ANALYSIS_SAVE_ERROR: 'ANALYSIS_SAVE_ERROR',
  RISK_SAVE_ERROR: 'RISK_SAVE_ERROR',

  // File validation errors
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  EMPTY_DOCUMENT: 'EMPTY_DOCUMENT',
  INVALID_ANALYSIS_TYPE: 'INVALID_ANALYSIS_TYPE'
} as const;

export interface ErrorResponse {
  code: ErrorCode;
  message: string;
  details?: any;
  severity: 'error' | 'warning' | 'info';
  timestamp: string;
  retryable?: boolean;
  action?: {
    label: string;
    onClick: () => void;
  };
}

export interface ErrorHandler {
  handleError: (error: Error | ContractAnalysisError) => ErrorResponse;
  isRetryable: (error: Error | ContractAnalysisError) => boolean;
  getErrorMessage: (error: Error | ContractAnalysisError) => string;
} 