// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.js';

const supabaseUrl = "https://abjuvmwpjapknuxqrefg.supabase.com";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFianV2bXdwamFwa251eHFyZWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjgxMzYsImV4cCI6MjA2NDA0NDEzNn0.HU_UW-vAcG-QOBljxtfCnlaMZehQs29hQ8Xx-ugq7RA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);